name: pyhpc-bench-cpu
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>3.6,<3.9
  - pip
  - pip:
    - click
    - aesara
    - numba
    - taichi
    - torch>=1.10
    - tensorflow>=2.0
    - jax[cpu]
