name: pyhpc-bench-gpu
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>3.6,<3.9
  - pip
  - cudnn>=8.2
  - cudatoolkit>=11.1
  - pip:
    - click
    - aesara
    - cupy
    - numba
    - torch>=1.10
    - tensorflow-gpu>=2.0
    - -f https://storage.googleapis.com/jax-releases/jax_releases.html
    - jax[cuda]
