name: pyhpc-bench-cpu
channels:
  - conda-forge
  - pytorch
  - nodefaults
dependencies:
  - python>3.6,<3.9
  - pip
  - numpy
  - pytorch>=1.10
  - tensorflow>=2.0
  - theano
  - numba
  - click
  - scipy
  - pip:
    - bohrium
    - -f https://storage.googleapis.com/jax-releases/jax_releases.html
    - jax[cpu]
